// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absence': string;
  'backBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
