// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'headBox': string;
  'header': string;
  'logo': string;
  'logoImg': string;
  'trigger': string;
  'usernameBox': string;
}
export const cssExports: CssExports;
export default cssExports;
